sudo: required
dist: trusty
language: ruby
rvm:
  - "2.0.0"
  - "2.2.5"
  - "2.3.1"
script: "PAYPAL_CLIENT_ID=YOUR_SANDBOX_CLIENT_ID PAYPAL_CLIENT_SECRET=YOUR_SANDBOX_CLIENT_SECRET bundle exec rspec"
sudo: false
notifications:
  recipients:
    - dl-paypal-payouts-sdk@paypal.com
  on_success: change
